#!/usr/bin/env bash
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo bash -c "echo 'deb http://nginx.org/packages/ubuntu/ xenial nginx' >> /etc/apt/sources.list.d/nginx.list"
sudo bash -c "echo 'deb-src http://nginx.org/packages/ubuntu/ xenial nginx' >> /etc/apt/sources.list.d/nginx.list"
wget http://nginx.org/keys/nginx_signing.key
sudo apt-key add nginx_signing.key
rm nginx_signing.key
sudo apt update
sudo apt install -y git nodejs nginx

git clone https://github.com/sqybi/online-interview-tool.git
cd online-interview-tool
cp config.js.example config.js

npm install
sudo npm install -g pm2

pm2 start index.js
pm2 save
# The following is generated by: pm2 startup systemd
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ${USER} --hp /home/${USER}
sudo systemctl enable pm2-${USER}.service

sudo mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.backup
sudo cp scripts/nginx_conf /etc/nginx/conf.d/online_interview_tool.conf

echo "Replace server_name with your domain in /etc/nginx/conf.d/online_interview_tool.conf. Command:"
echo "sudo vim /etc/nginx/conf.d/online_interview_tool.conf"
echo ""
echo "Replace document_creation_token with randomly generated string in ~/online-interview-tool/config.js. Command:"
echo "vim ~/online-interview-tool/config.js"
echo ""
echo "Reboot after that to apply changes!!!"
echo "Reboot after that to apply changes!!!"
echo "Reboot after that to apply changes!!!"